
import "@/app/globals.css";
import UserLayout from "@/components/layouts/user";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <UserLayout>
        {children}
    </UserLayout>
  );
}
